---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - blackbox-exporter
  # - generic-rules
  # - goldilocks
  # - grafana
  # - intel-gpu-exporter
  - kube-prometheus-stack
  # - loki
  # - pushgateway
  # - smartctl-exporter
  # - snmp-exporter
  # - speedtest-exporter
  # - thanos
  # - uptimerobot-heartbeat
  # - vector
  # - vpa
