# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:tlkPM+xhrtzBph8kVEmq1wbxbjWaKA==,iv:KZ9PdASNAAiji/y0D+HjRuSyqhyIF41pnFP0LWLC+is=,tag:XI0vi97xMlH0wicoDUACyQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Upemy9KmTa/TBPDN6+HGW2ayUDI=,iv:Q6hsUVv4H2RG1B0xBxoOCVwdV2gzemylcindedi3H1s=,tag:YwytVsNUHQQmmxtMjbqZ3Q==,type:str]
    SECRET_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:ZCvBtkAEnI5AlKlE2P3mzZksKBY6rUaGj5UWsXir2z0KTEwfsKduizaYggo00N7n5yqNH/2QyiGxLhh0cVriALlTFS5ddlOf,iv:NEUfNhnbGnNynjvcnLWB4kAEvCPGjcY7wXjWjhn6LX4=,tag:0Qy/vgQ0ryYR8Tw6ACyD2g==,type:str]
    SECRET_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:QwAunCJB//Ag5PBSvNvL0yiw3Ra/gmTCzo53m0zUefRZiAE=,iv:RLEBsjPVQC1yfkO6k3B/PnQzQDpUtbYM9Ikg9MD6kSg=,tag:hzqXMghlhB3OoaMuinjvqg==,type:str]
    SECRET_WHITELIST: ENC[AES256_GCM,data:voSXqJcynVXT+QeoAJaySbT0CLottq/6jm4sUzVISuOOfsH9B2pPOcedcMm6uIqAUvs=,iv:SmSe+wvaqETXdHcc69375casFUC48I03LvkP5jQbYt4=,tag:8os1kCEtD72ZVbn75052iA==,type:str]
    SECRET_PUSHOVER_USERKEY: ENC[AES256_GCM,data:6wYTBxxMeBk1kYFMbtrHc3+Ay1OAUyg6AClxAs16,iv:ePMCxPZOexih2g225RXyvXSCT575pUcwYbp4K1Yxk6w=,tag:zmbdh87wZWfckORRDcDSQg==,type:str]
    SECRET_PUSHOVER_ALERT_MANAGER_APIKEY: ENC[AES256_GCM,data:RrO21Nr94PtE2n404IaD1tQBga6I3FekbvYpaszJ,iv:ZCyV4Hqis1yFK+tfNDfSKVovhTKe3zXN7ltYcgvDdjU=,tag:ASHeG5U1kqRryt7Feddttg==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:pM/ss1u4cekVM74zqd1vug==,iv:LQqGRBmTnaYXeSiXija3UB5TKObquouxWQ/IAbvu/tI=,tag:gEnFint5MdcMduERYiWKtQ==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:Xs4OZ+MaRHywabqmhOyBSgwC2RgVmQ7Q/9P884HwySc=,iv:7graXCIf2jihmFO/g6T9FBYis0KJlQNZB1ljqJlcnz8=,tag:HonsX7wVwnd34bUWIlQapw==,type:str]
    SECRET_TRUENAS_APIKEY: ENC[AES256_GCM,data:bDDtJLbCvtITT8NF37SMwKvwtwfr7KkQQfs2iuBu9Y/mvEEhdmLZ2aj2WYeCuVygkdl5aA5GP54Etyhl1Cvm/YTb,iv:woWTBBYDPiXcvjj9qR8+SWLobMQSejNq2LJTZoh3Trw=,tag:pBI8jqP7eeTxuOVLJTr8Qw==,type:str]
    SECRET_TRUENAS_PASSWORD: ENC[AES256_GCM,data:O7+doWzLB1d768s=,iv:8Ri32VUoxd6B2unfnTUpkR9zT03KKMeV3Nm0HToUo/o=,tag:4TY8MdCV6R6KF0fBLu6zTQ==,type:str]
    BOOSTRAP_RANCHER_PASSWORD: ENC[AES256_GCM,data:mDveiKqiHW2kdEo=,iv:BNFsUcGNrWD0aj0S5l9kP1VECkW+Vh5oFpPrlTvezfk=,tag:cRn3fBI+fGVdlQgUd/DAHw==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:Af8JWzR0RysLdcTbcvxoso1iIpdxmNz5ky7CEpbItndJOMh+fwO2RA==,iv:/cBioPPbV01iVa7g7UAqAOcHN4ST5UjpDjGj/MCYYro=,tag:sXNCrPeGU2eEOOnko+Kc2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dx37e63lm0lfw6mat5ftdn7kt0gxh0s9227ktak39x3k8rk0l4jsz36ma8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQzNDQ1hJdzZ5K0xWa0Zp
            cTJiSGZ0TEJ5TG9WMEp1QW1RdlAzZXN6WTE0CkNwaXRtN3JFSzlCQzhCdWowdWt3
            NGM0TS9kd0JTdXh5YlVyMGNJdHYyWWsKLS0tIEF3Z1FQZGZlRmhJNCs3NkMxdDM2
            ckV4RkEwWHJvTnhCTXY0cHZKSmREaHcK2HnqnF5fkqA4/sHRLPlE7EvPcKOQsAyI
            DbrP0UB82tfkGn0D56ERUP3wTrXeYh3Zw1PO754R8vzhvTDoay9xYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-29T03:16:28Z"
    mac: ENC[AES256_GCM,data:k31CmGB45mGtC2OTFK0bRaOP5mZ2dbNOyW3Db0qULr62qCh8QjbX0pOQQmEvxURvb1xcQ1/hvOhY9akDxGtGsxGD+0tE3l26wH9lSXj3a2ne3zdcu15qTtxopX7fheVtZ8b0VewnoQk4FliMvEpfnkGMq1UTW0yuWCYDQFYAEjU=,iv:EMPnu2LfDCFhxjs9RCTK+eRWwJDeuPUAJ/LzYjO1DIY=,tag:CPNlLhAck0qctM40/spvGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
