---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Detroit
  METALLB_LB_RANGE: 192.168.0.55-192.168.0.65
  METALLB_K8S_GATEWAY_ADDR: 192.168.0.56
  METALLB_INGRESS_ADDR: 192.168.0.55
