kind: Secret
ansible_user: ENC[AES256_GCM,data:xKVJxA==,iv:y5V3JcwJT1VGtvcB+CASKgz8LgE8djY8IV490Z9T+V8=,tag:WHC5PLbOoZ2c6ChRplP+UQ==,type:str]
ansible_become_pass: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dx37e63lm0lfw6mat5ftdn7kt0gxh0s9227ktak39x3k8rk0l4jsz36ma8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNEg5dUJxalljRGR1Vnc4
            cGNKYkxmVkNhM2IrbGtXWGkvTDcxQmd4QXlBCkxZK0RHeFlEZGMvY0pzZmFNWkhQ
            eUk4b0dKeTlGcERTZWhnYzliUzFkWHcKLS0tIG1pdGFHZGExcWxWTXRWczZNNUxC
            c2VFYnNQcmVtMzd1ZGhEWGJUbzBtS00KyYKVKiXhvFJThnodL0XPkX2uamZjNxLz
            OQ2CBRG50SQUMcUkE+oWE4fs0kOBt1XZO/jNGCHRpM0Qn+/AapxV9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-28T17:41:01Z"
    mac: ENC[AES256_GCM,data:GJ+2aGxu1phH1GKC2s7vKhGPsyz/d8YF3CoT0/eVu+fYiyOJ2J2J4+fJ2f3nWFmAynHU17U5YaDBLt7OwBx3byfn2nLmuAcpnz+DhNkSbwkqslJU32JTy3HGJPU4LagTqnnFVnAi2/+L1aJCqwdmxo28Jr8A2AuZiZkcaAeiy1Q=,iv:Q0OiP2xUc/nW+4nkFGcv12+VkFRUIUb6/QxaCsKV6vI=,tag:VhfsxyJDeUSoC0GbV1xODA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
