---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - democratic-csi
  - system-upgrade-controller
  - cloudnative-pg
  - kube-prometheus-stack
  - rook-ceph
