---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  storageClassName: csi-truenas-nfs
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: storage-minio
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-truenas-nfs
  resources:
    requests:
      storage: 1000Gi
