# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: default
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:9AY3Vw==,iv:m+61JyYkqgt/wi5iEgHUtwxniuzs4/IGTLoaIQXiSgU=,tag:owc6WqdJpfRHtEEwp9rSeg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:k3F0IUPjnBPEm9rQ7nAvSHbPf/TnQKJr,iv:DB7dwUJn8lQUHZgO9r2SX4jGlFhG3/z7LwzcBoYs90w=,tag:7rRCmwl2xw8zCtERStHSVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dx37e63lm0lfw6mat5ftdn7kt0gxh0s9227ktak39x3k8rk0l4jsz36ma8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWWI1WUdRVFJ5UUk2L24y
            VFNMSkNhZERWSHMySHBjVWtmK0FVQUNvekY4ClBTRlp4cFlZcEk0bXhlTFdhSk14
            Y1czKzd2NFdJWngwR2E1ZlJ5ZUFWMXcKLS0tIGlNOHFjcys5ZVlCS0VvdUloSDJP
            SjFKUUFiZjhOLzZaSUl2RHdJMkRQM28Kfl7N1yjpbyy7Hy8xlTCO0wg3Ach0xC6L
            KwwZXhm3J6QO+yehQibLUqJruIyMRLRQjohOgQMwq0uTQ79VQDmy9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-30T23:48:24Z"
    mac: ENC[AES256_GCM,data:jGUtWxLqEPkiSU+H7Lqb2ekurUG2Qg2fnsjmaKVtqRDlEU9OuZXiQtuAVcbWukgnGx70gSpXB36Vby20lkviYvCD+/ZuK4XHOW+vfHhJZne8WuUj3nj2HmV8PdTl9MwhAx2eNauPK2ilIjuKkUjfzS+x5QmstzRejmaR8DNTJEw=,iv:JimI2kjYB0HAttlOL1HNXqnEoKl+cKC09Yrgrs1QdDA=,tag:dJUbCvXXa2imkDzua8pwYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
